export const SystemConstants = {
  TIE_MSG: "Tied!",
  WIN_MSG: "You Won!",
  LOST_MSG: "You Lost!",
  LEFT_MSG: "The other player has left and close the connection",
  REPLAY_MSG: "Play one more?",
  GAME_NOT_START_MSG: "Game has not started yet!",
  GAME_START_MSG: "Game started",
  INVALID_MSG: "Invalid move",
  NOT_MOVE_YET_MSG: "It's not your move yet.",
  WAITING_MSG: "Waiting for another player",
  PLAYER_X_MSG: "You are 'Player X.",
  PLAYER_O_MSG: "You are 'Player O.",
  USERNAME_EXISTS_MSG: "Username already exists!",
  STARTED: 1,
  TIED: 2,
  FINISHED: 3,
  NORMALIZE: (str = "") => str.replace(/[\s\n]/g, ""),
  GEN_KEY: () => Math.round(Math.random() * 1000).toString(),
  roomPrefix: "game_room_",
  PROGRESS_KEY: 'progress',
  OVER_KEY: "over",
  REPLAY_KEY: "replay",
  INFO_KEY: "info",
  UNAME_EXISTS_KEY: "uname-exists",
  SCOREBOARD_KEY: "scoreboard",
  CONNECTION_KEY: 'connection',
  NEW_USER_CONNECTED_MSG: `New user connected to the server: `,
  ENTER_KEY: "enter",
  JOIN_KEY: "enter-join",
  MOVE_KEY: "move",
  TIE_KEY: "tie",
  REPLAY_CONFIRM_KEY: "replayConfirm",
  DISCONNECT_KEY: "disconnect",
  ROOM_LIST: 'roomList',
  ROOM_LIMIT_MSG: 'Only 10 room can be created;',
  ROOM_LIMIT: 9
} as const;